theme: minima

minima:
  nav_pages:
    - about.md
    - work.md
    - contact.md
  social_links:
    url: https://www.linkedin.com/in/natasha-koussa-5a585522/
    title: LinkedIn


author:
  name: Natasha Koussa
  email: natasha.c.koussa@gmail.com


