# Add to plugins: list
plugins:
  - jekyll-remote-theme

# set up remote_theme
remote_theme: jekyll/minima

minima:
  nav_pages:
    - about.md
    - work.md
    - contact.md
    - assets/docs/test2.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/nkoussa"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/natasha-koussa-5a585522/"



author:
  name: Natasha Koussa
  email: natasha.c.koussa@gmail.com


